"use strict";
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const products=[{name:"Café Andino · 500 g",sku:"CAF-500",stock:8,price:12.5,color:"#8b5e3c",emoji:"☕"},{name:"Salsa de Mango",sku:"SAL-240",stock:17,price:6.75,color:"#e99b31",emoji:"🥭"},{name:"Tortillas Artesanales",sku:"TOR-012",stock:0,price:4.9,color:"#d6ad72",emoji:"🌮"}];
const renderProducts=()=>{const host=$("#products");if(host)host.innerHTML=products.map(p=>`<div class="product"><i style="background:${p.color}">${p.emoji}</i><span><b>${p.name}</b><small>${p.sku} · $${p.price.toFixed(2)}</small></span><em class="${p.stock?'low':'out'}">${p.stock?p.stock+' '+tr("left"):tr("Out")}</em><button aria-label="${tr("More options")}">•••</button></div>`).join("")};
const modal=$("#modal"), form=$("#productForm"), photo=$("#photo"), upload=$("#upload"), taxToggle=$("#taxToggle"), taxValue=$("#taxValue"), stock=$("#stock");
const mobileSectionsToggle=$("#mobileSectionsToggle"), workspaceSections=$("#workspaceSections");
const closeMenu=()=>{if(!mobileSectionsToggle||!workspaceSections)return;workspaceSections.classList.remove("mobile-open");mobileSectionsToggle.classList.remove("open");mobileSectionsToggle.setAttribute("aria-expanded","false")};
const toggleMenu=()=>{if(!mobileSectionsToggle||!workspaceSections)return;const open=!workspaceSections.classList.contains("mobile-open");workspaceSections.classList.toggle("mobile-open",open);mobileSectionsToggle.classList.toggle("open",open);mobileSectionsToggle.setAttribute("aria-expanded",String(open))};
mobileSectionsToggle?.addEventListener("click",toggleMenu);
document.addEventListener("click",event=>{if(innerWidth<=599&&workspaceSections?.classList.contains("mobile-open")&&!event.target.closest("#workspaceSections")&&!event.target.closest("#mobileSectionsToggle"))closeMenu()});
window.addEventListener("resize",()=>{if(innerWidth>599)closeMenu()});
let activeView="";
let activeLanguage=localStorage.getItem("marxia-language")==="es"?"es":"en";
const es={
"Overview":"Resumen","Orders":"Pedidos","Products":"Productos","Inventory":"Inventario","Marketplace":"Mercado","Logistics":"Logística","Accounting":"Contabilidad","Reports":"Informes","Profile":"Perfil","Settings":"Ajustes","Tech Support":"Soporte técnico","Add product":"Agregar producto","Good morning, Gabriel":"Buenos días, Gabriel","Here’s what’s happening across your business.":"Esto es lo que está sucediendo en tu negocio.","Sell":"Vender","Buy for my business":"Comprar para mi negocio","3 items need your attention":"3 artículos necesitan tu atención","Two products are running low and one order is waiting to be dispatched.":"Dos productos tienen pocas existencias y un pedido está pendiente de envío.","Review now":"Revisar ahora","Business pulse":"Pulso del negocio","Performance at a glance":"Rendimiento de un vistazo","Last 7 days":"Últimos 7 días","Last 30 days":"Últimos 30 días","This year":"Este año","Go back":"Volver","Open":"Abrir","Workspace":"Espacio de trabajo","Account shortcuts":"Accesos directos de la cuenta","Notifications":"Notificaciones","Close":"Cerrar","Change language":"Cambiar idioma","Switch appearance":"Cambiar apariencia",
"12.4% business growth":"12.4% de crecimiento del negocio","6 waiting":"6 en espera","248 orders this month":"248 pedidos este mes","86 active":"86 activos","4 added this month":"4 agregados este mes","3 low-stock items":"3 artículos con pocas existencias","42 sellers":"42 vendedores","8 new connections":"8 conexiones nuevas","14 active":"14 activos","96.8% on-time":"96.8% a tiempo","33.8% net margin":"33.8% de margen neto","12 ready":"12 listos","Updated today":"Actualizado hoy","Updated yesterday":"Actualizado ayer","trend":"tendencia","left":"restantes","Out":"Agotado","More options":"Más opciones",
"6 orders waiting to be fulfilled":"6 pedidos pendientes de preparación","Current orders":"Pedidos actuales","Export list":"Exportar lista","Placed today · Payment confirmed":"Realizado hoy · Pago confirmado","Ready":"Listo","Packing":"Preparando","New":"Nuevo","Manage pricing, availability, and catalog details":"Administra precios, disponibilidad y detalles del catálogo","Product catalog":"Catálogo de productos","Stock levels and restock priorities":"Niveles de inventario y prioridades de reposición","Inventory health":"Estado del inventario","Total stock value":"Valor total del inventario","Needs attention":"Requiere atención","Create restock order":"Crear orden de reposición",
"Discover SMB suppliers and business partners":"Descubre proveedores y socios comerciales de PYMES","Wholesale coffee · Quito":"Café al por mayor · Quito","Produce · Guayaquil":"Productos frescos · Guayaquil","Sustainable packaging · Cuenca":"Empaques sostenibles · Cuenca","Handmade goods · Loja":"Productos artesanales · Loja","View business":"Ver negocio","Shipments, couriers, and delivery performance":"Envíos, transportistas y rendimiento de entregas","Active deliveries":"Entregas activas","12 on time · 2 require attention":"12 a tiempo · 2 requieren atención","Latest shipments":"Envíos recientes","Courier assigned":"Transportista asignado","In transit":"En tránsito","Arrives today":"Llega hoy","On time":"A tiempo","Delivered":"Entregado",
"Revenue, expenses, tax, and cash flow":"Ingresos, gastos, impuestos y flujo de caja","INCOME":"INGRESOS","EXPENSES":"GASTOS","TAX SET ASIDE":"RESERVA PARA IMPUESTOS","Current":"Actual","Cash-flow trend":"Tendencia del flujo de caja","Open books":"Abrir libros","Business intelligence and downloadable summaries":"Inteligencia empresarial y resúmenes descargables","Sales performance":"Rendimiento de ventas","Revenue, order value, and product trends":"Ingresos, valor de pedidos y tendencias de productos","Inventory movement":"Movimiento de inventario","Stock levels, turnover, and restock history":"Niveles, rotación e historial de reposición","Customer activity":"Actividad de clientes","Repeat orders and customer growth":"Pedidos recurrentes y crecimiento de clientes","Logistics performance":"Rendimiento logístico","Delivery time, cost, and courier quality":"Tiempo, costo y calidad de entrega","Tax summary":"Resumen fiscal","VAT collected and tax set aside":"IVA recaudado y reserva fiscal","Profit and loss":"Pérdidas y ganancias","Income, expenses, and net margin":"Ingresos, gastos y margen neto","August 2026":"Agosto de 2026","Open report":"Abrir informe",
"Business Settings":"Ajustes del negocio","Profile and business identity settings":"Ajustes del perfil y la identidad del negocio","Owner · Full access":"Propietario · Acceso total","Account name":"Nombre de la cuenta","Account email":"Correo de la cuenta","Edit profile":"Editar perfil","Business identity preview":"Vista previa de la identidad del negocio","Crafted with purpose":"Creado con propósito","Business logo":"Logotipo del negocio","Square PNG, JPG, or WebP works best.":"Un archivo PNG, JPG o WebP cuadrado funciona mejor.","Business name":"Nombre del negocio","Business motto":"Lema del negocio","Save business identity":"Guardar identidad del negocio","Your business":"Tu negocio","Your motto":"Tu lema","Business identity saved.":"Identidad del negocio guardada.",
"Help with your account, catalog, orders, or operations":"Ayuda con tu cuenta, catálogo, pedidos u operaciones","Marxia Tech Support":"Soporte técnico de Marxia","Verify your identity and explicitly approve temporary support access.":"Verifica tu identidad y autoriza expresamente el acceso temporal de soporte.","Password":"Contraseña","Enter password to verify":"Ingresa tu contraseña para verificar","Allow Tech Support Access to my Account":"Permitir que Soporte técnico acceda a mi cuenta","Temporary, scoped, and auditable access.":"Acceso temporal, limitado y auditable.","Acknowledge":"Confirmar","Acknowledged":"Confirmado","Your password is used only to verify your identity. Tech Support cannot view it, and this prototype does not store it.":"Tu contraseña se usa únicamente para verificar tu identidad. Soporte técnico no puede verla y este prototipo no la almacena.","Passwords are never visible to Tech Support or included in the request.":"Las contraseñas nunca son visibles para Soporte técnico ni se incluyen en la solicitud.","Start Support Request":"Iniciar solicitud de soporte","Quick Help":"Ayuda rápida","Product and inventory help":"Ayuda con productos e inventario","Images, pricing, stock, and catalog updates":"Imágenes, precios, existencias y actualizaciones del catálogo","Orders and logistics":"Pedidos y logística","Fulfillment, dispatch, and delivery issues":"Problemas de preparación, despacho y entrega","Account access":"Acceso a la cuenta","Profile, permissions, and sign-in support":"Ayuda con perfil, permisos e inicio de sesión","Support request prepared. Your password was not included or stored.":"Solicitud de soporte preparada. Tu contraseña no fue incluida ni almacenada.",
"NEW PRODUCT":"PRODUCTO NUEVO","Add to your catalog":"Agregar a tu catálogo","Photograph it, price it, and start selling.":"Toma una foto, define el precio y comienza a vender.","Product image":"Imagen del producto","Take a picture or upload":"Tomar una foto o cargar una imagen","JPG, PNG · up to 10 MB":"JPG, PNG · hasta 10 MB","Product name":"Nombre del producto","e.g. Cacao Nacional":"p. ej., Cacao Nacional","Price (USD)":"Precio (USD)","Auto-generated":"Generado automáticamente","Stock quantity":"Cantidad disponible","Add VAT / tax":"Agregar IVA / impuesto","Calculated at checkout and shown on invoices":"Se calcula al pagar y se muestra en las facturas","Mark product as not in stock":"Marcar producto como agotado","Cancel":"Cancelar","Save product":"Guardar producto","Product saved":"Producto guardado","Your product is now in the catalog and ready to publish.":"Tu producto ya está en el catálogo y listo para publicarse.","Back to dashboard":"Volver al panel","Search orders, products, customers…":"Buscar pedidos, productos y clientes…","Open Settings to update your business logo and motto":"Abrir Ajustes para actualizar el logotipo y el lema del negocio","Profile and Settings":"Perfil y ajustes","Open Tech Support":"Abrir Soporte técnico","Add a new product":"Agregar un producto nuevo","Switch Light or Dark appearance":"Cambiar entre apariencia clara y oscura"
};
const tr=text=>activeLanguage==="es"?(es[text]||text):text;
Object.assign(es,{"FRIDAY, AUGUST 28":"VIERNES, 28 DE AGOSTO","Delivered 10:42":"Entregado 10:42","Business overview":"Resumen del negocio","Review and fulfill orders":"Revisar y preparar pedidos","Manage your product catalog":"Administrar tu catálogo de productos","Track stock and restocking":"Controlar existencias y reposición","Find SMB suppliers and partners":"Encontrar proveedores y socios PYMES","Manage shipments and couriers":"Administrar envíos y transportistas","Review income, expenses, and tax":"Revisar ingresos, gastos e impuestos","Open business reports":"Abrir informes del negocio"});
const en=Object.fromEntries(Object.entries(es).map(([key,value])=>[value,key]));
const localize=(root=document)=>{const translate=value=>{const lead=value.match(/^\s*/)[0],tail=value.match(/\s*$/)[0],clean=value.trim(),source=en[clean]||clean;return clean&&es[source]?lead+tr(source)+tail:value};const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode())node.nodeValue=translate(node.nodeValue);const elements=root.nodeType===1?[root,...root.querySelectorAll("*")]:[...root.querySelectorAll("*")];elements.forEach(el=>["placeholder","aria-label","title","data-tooltip"].forEach(name=>{if(el.hasAttribute(name))el.setAttribute(name,translate(el.getAttribute(name)))}))};
const businessViews=new Set(["Overview","Orders","Products","Inventory","Marketplace","Logistics","Accounting","Reports","Settings","Support"]);
const clearDashboardView=()=>{activeView="";$$('[data-view]').forEach(button=>{button.classList.remove("active");button.setAttribute("aria-pressed","false")});$(".section-title").hidden=true;viewHost.innerHTML="";viewHost.hidden=true};
const selectView=view=>{if(activeView===view){clearDashboardView();closeMenu();return}activeView=view;$$('[data-view]').forEach(button=>{const selected=button.dataset.view===view;button.classList.toggle("active",selected);button.setAttribute("aria-pressed",selected?"true":"false")});if(businessViews.has(view))renderDashboardView(view);closeMenu()};
$$('[data-view]').forEach(b=>b.onclick=()=>selectView(b.dataset.view));
$(".notice>button").onclick=()=>selectView("Inventory");
$$('.mode button').forEach(b=>b.onclick=()=>{$$('.mode button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});

const viewHost=$("#viewHost");
const overviewCards=[
 {view:"Overview",icon:"▦",label:"Overview",value:"$12,480",note:"12.4% business growth",points:[16,22,20,28,31,39,44],accent:"#4338ca",tint:"#eef2ff"},
 {view:"Orders",icon:"▣",label:"Orders",value:"6 waiting",note:"248 orders this month",points:[12,18,17,25,23,31,37],accent:"#0369a1",tint:"#e0f2fe"},
 {view:"Products",icon:"□",label:"Products",value:"86 active",note:"4 added this month",points:[20,22,24,27,29,32,35],accent:"#0f766e",tint:"#ccfbf1"},
 {view:"Inventory",icon:"▤",label:"Inventory",value:"$8,940",note:"3 low-stock items",points:[38,35,32,29,27,23,25],accent:"#a16207",tint:"#fef3c7"},
 {view:"Marketplace",icon:"⌂",label:"Marketplace",value:"42 sellers",note:"8 new connections",points:[11,15,19,18,25,29,36],accent:"#7e22ce",tint:"#f3e8ff"},
 {view:"Logistics",icon:"▱",label:"Logistics",value:"14 active",note:"96.8% on-time",points:[18,24,22,30,34,32,40],accent:"#0e7490",tint:"#cffafe"},
 {view:"Accounting",icon:"$",label:"Accounting",value:"$4,216",note:"33.8% net margin",points:[14,17,21,26,25,32,38],accent:"#166534",tint:"#dcfce7"},
 {view:"Reports",icon:"▥",label:"Reports",value:"12 ready",note:"Updated today",points:[10,14,13,19,24,28,34],accent:"#be123c",tint:"#ffe4e6"}
];
const orders=[["#MX-1048","Ana Rivera","$84.50","Ready"],["#MX-1047","Tienda Verde","$236.00","Packing"],["#MX-1046","Luis Herrera","$48.20","New"],["#MX-1045","Mercado Sol","$319.40","Ready"],["#MX-1044","María León","$72.00","Packing"],["#MX-1043","Café Norte","$155.75","New"]];
const pageHead=(title,subtitle)=>`<div class="detail-head"><button class="back-button" data-back>‹ ${tr("Go back")}</button><span><h2>${tr(title)}</h2><small>${tr(subtitle)}</small></span></div>`;
const overviewTemplate=()=>`<div class="overview-cards">${overviewCards.map(c=>`<button class="pulse-card" data-open-view="${c.view}" data-tooltip="${tr("Open")} ${tr(c.label)}" style="--accent:${c.accent};--tint:${c.tint}"><span class="pulse-icon">${c.icon}</span><small>${tr(c.label).toUpperCase()}</small><strong>${tr(c.value)}</strong><canvas class="sparkline" width="240" height="54" data-color="${c.accent}" data-points="${c.points.join(",")}" aria-label="${tr(c.label)} ${tr("trend")}"></canvas><em>${tr(c.note)}</em></button>`).join("")}</div>`;
const details={
 Orders:()=>`${pageHead("Orders","6 orders waiting to be fulfilled")}<section class="detail-card"><div class="detail-toolbar"><b>Current orders</b><button>Export list</button></div><div class="data-list">${orders.map(o=>`<div><span><b>${o[0]} · ${o[1]}</b><small>Placed today · Payment confirmed</small></span><strong>${o[2]}</strong><em>${o[3]}</em></div>`).join("")}</div></section>`,
 Products:()=>`${pageHead("Products","Manage pricing, availability, and catalog details")}<section class="detail-card"><div class="detail-toolbar"><b>Product catalog</b><button data-add>＋ Add product</button></div><div id="products" class="product-catalog"></div></section>`,
 Inventory:()=>`${pageHead("Inventory","Stock levels and restock priorities")}<section class="detail-grid"><article class="detail-card"><h3>Inventory health</h3><strong class="big-number">$8,940.00</strong><small>Total stock value</small><canvas class="sparkline large" width="500" height="110" data-points="38,36,34,31,29,27,25"></canvas></article><article class="detail-card"><h3>Needs attention</h3><div id="products"></div><button class="outline">Create restock order</button></article></section>`,
 Marketplace:()=>`${pageHead("Marketplace","Discover SMB suppliers and business partners")}<section class="market-grid">${[["Andes Coffee Co.","Wholesale coffee · Quito","4.9"],["Costa Fresh Foods","Produce · Guayaquil","4.8"],["EcoPack Ecuador","Sustainable packaging · Cuenca","4.7"],["Ruta Artesanal","Handmade goods · Loja","4.9"]].map(x=>`<article class="detail-card market-card"><i>CM</i><span><h3>${x[0]}</h3><small>${x[1]}</small></span><b>★ ${x[2]}</b><button>View business</button></article>`).join("")}</section>`,
 Logistics:()=>`${pageHead("Logistics","Shipments, couriers, and delivery performance")}<section class="detail-grid"><article class="detail-card"><h3>Active deliveries</h3><strong class="big-number">14</strong><small>12 on time · 2 require attention</small><canvas class="sparkline large" width="500" height="110" data-points="18,24,22,30,34,32,40"></canvas></article><article class="detail-card"><h3>Latest shipments</h3><div class="data-list compact"><div><span><b>MX-LG-208 · Quito</b><small>Courier assigned</small></span><em>In transit</em></div><div><span><b>MX-LG-207 · Cuenca</b><small>Arrives today</small></span><em>On time</em></div><div><span><b>MX-LG-206 · Manta</b><small>Delivered 10:42</small></span><em>Delivered</em></div></div></article></section>`,
 Accounting:()=>`${pageHead("Accounting","Revenue, expenses, tax, and cash flow")}<section class="account-summary"><article class="detail-card"><small>INCOME</small><strong>$10,860.00</strong><em>↑ 11.2%</em></article><article class="detail-card"><small>EXPENSES</small><strong>$5,172.30</strong><em>↓ 2.4%</em></article><article class="detail-card"><small>TAX SET ASIDE</small><strong>$1,245.60</strong><em>Current</em></article></section><section class="detail-card"><div class="detail-toolbar"><b>Cash-flow trend</b><button>Open books</button></div><canvas class="sparkline accounting-chart" width="900" height="150" data-points="14,18,22,20,29,34,32,41,46"></canvas></section>`,
 Reports:()=>`${pageHead("Reports","Business intelligence and downloadable summaries")}<section class="report-grid">${[["Sales performance","Revenue, order value, and product trends","Updated today"],["Inventory movement","Stock levels, turnover, and restock history","Updated today"],["Customer activity","Repeat orders and customer growth","Updated yesterday"],["Logistics performance","Delivery time, cost, and courier quality","Updated today"],["Tax summary","VAT collected and tax set aside","August 2026"],["Profit and loss","Income, expenses, and net margin","August 2026"]].map(x=>`<article class="detail-card report-card"><i>▥</i><span><h3>${x[0]}</h3><small>${x[1]}</small><em>${x[2]}</em></span><button>Open report</button></article>`).join("")}</section>`,
 Settings:()=>`${pageHead("Business Settings","Profile and business identity settings")}<article class="detail-card profile-settings-card"><div><i>GS</i><span><h3>Profile</h3><small>Owner · Full access</small></span></div><p><span>Account name</span><b>Gabriel S.</b></p><p><span>Account email</span><b>gabriel@cacaoymas.ec</b></p><button>Edit profile</button></article><section class="settings-layout"><article class="detail-card brand-preview"><span class="tenant-logo preview-logo" id="settingsLogoPreview"><b>CM</b></span><h3>Business identity preview</h3><strong id="settingsNamePreview">Cacao & Más</strong><small id="settingsMottoPreview">Crafted with purpose</small></article><form class="detail-card settings-form" id="brandSettingsForm"><label>Business logo<input id="brandLogoFile" type="file" accept="image/png,image/jpeg,image/webp"><small>Square PNG, JPG, or WebP works best.</small></label><label>Business name<input id="brandNameInput" maxlength="40" value="Cacao & Más"></label><label>Business motto<input id="brandMottoInput" maxlength="70" value="Crafted with purpose"></label><button class="primary" type="submit">Save business identity</button><p id="brandSaveStatus" role="status"></p></form></section>`,
 Support:()=>`${pageHead("Tech Support","Help with your account, catalog, orders, or operations")}<section class="support-workspace"><form class="detail-card support-access-form" id="supportAccessForm"><div class="support-title"><i>☏</i><span><h3>Marxia Tech Support</h3><p>Verify your identity and explicitly approve temporary support access.</p></span></div><label>Account email<input id="supportEmail" type="email" autocomplete="email" required placeholder="you@business.com"></label><label>Password<input id="supportPassword" type="password" autocomplete="current-password" required placeholder="Enter password to verify"></label><div class="acknowledge-row"><span><b>Allow Tech Support Access to my Account</b><small>Temporary, scoped, and auditable access.</small></span><button id="supportAcknowledge" type="button" aria-pressed="false">Acknowledge</button></div><p class="support-note"><button type="button" data-tooltip="Your password is used only to verify your identity. Tech Support cannot view it, and this prototype does not store it.">?</button> Passwords are never visible to Tech Support or included in the request.</p></form><aside class="support-side"><button class="primary support-start" id="startSupportRequest" type="button" disabled>Start Support Request</button><article class="detail-card quick-help"><h3>Quick Help</h3><div class="data-list compact"><div><span><b>Product and inventory help</b><small>Images, pricing, stock, and catalog updates</small></span></div><div><span><b>Orders and logistics</b><small>Fulfillment, dispatch, and delivery issues</small></span></div><div><span><b>Account access</b><small>Profile, permissions, and sign-in support</small></span></div></div></article><p id="supportStatus" class="support-status" role="status"></p></aside></section>`
};
const drawSparklines=()=>{$$(".sparkline").forEach(canvas=>{const values=canvas.dataset.points.split(",").map(Number),ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,pad=5,min=Math.min(...values),max=Math.max(...values);ctx.clearRect(0,0,w,h);ctx.strokeStyle=canvas.dataset.color||"#2b6b5c";ctx.lineWidth=3;ctx.lineJoin="round";ctx.beginPath();values.forEach((v,i)=>{const x=pad+i*(w-pad*2)/(values.length-1),y=h-pad-(v-min)/(max-min||1)*(h-pad*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})};
function renderDashboardView(view="Overview"){$(".section-title").hidden=false;viewHost.hidden=false;viewHost.innerHTML=view==="Overview"?overviewTemplate():(details[view]?.()||overviewTemplate());$$("[data-open-view]",viewHost).forEach(b=>b.onclick=()=>selectView(b.dataset.openView));$$("[data-back]",viewHost).forEach(b=>b.onclick=()=>selectView("Overview"));$$("[data-add]",viewHost).forEach(b=>b.onclick=openModal);renderProducts();localize(viewHost);drawSparklines();if(view==="Settings")wireBrandSettings();if(view==="Support")wireSupportRequest();wireTooltips();viewHost.scrollIntoView({behavior:"smooth",block:"start"})}
const defaultBrand={name:"Cacao & Más",motto:"Crafted with purpose",logo:""};
const loadBrand=()=>{try{return{...defaultBrand,...JSON.parse(localStorage.getItem("marxia-smb-brand")||"{}")}}catch{return{...defaultBrand}}};
let brandState=loadBrand(),pendingLogo=brandState.logo;
const renderLogo=(host,logo=brandState.logo)=>{if(!host)return;host.innerHTML=logo?`<img src="${logo}" alt="">`:`<b>${brandState.name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"SM"}</b>`};
const applyBrand=()=>{$("#tenantName").textContent=brandState.name;$("#tenantMotto").textContent=brandState.motto;renderLogo($("#tenantLogo"))};
function wireBrandSettings(){const form=$("#brandSettingsForm"),name=$("#brandNameInput"),motto=$("#brandMottoInput"),file=$("#brandLogoFile"),status=$("#brandSaveStatus");name.value=brandState.name;motto.value=brandState.motto;$("#settingsNamePreview").textContent=brandState.name;$("#settingsMottoPreview").textContent=brandState.motto;renderLogo($("#settingsLogoPreview"));const preview=()=>{$("#settingsNamePreview").textContent=name.value||tr("Your business");$("#settingsMottoPreview").textContent=motto.value||tr("Your motto")};name.oninput=preview;motto.oninput=preview;file.onchange=()=>{const selected=file.files[0];if(!selected)return;const reader=new FileReader();reader.onload=()=>{pendingLogo=reader.result;renderLogo($("#settingsLogoPreview"),pendingLogo)};reader.readAsDataURL(selected)};form.onsubmit=e=>{e.preventDefault();brandState={name:name.value.trim()||defaultBrand.name,motto:motto.value.trim()||defaultBrand.motto,logo:pendingLogo};try{localStorage.setItem("marxia-smb-brand",JSON.stringify(brandState))}catch{}applyBrand();status.textContent=tr("Business identity saved.")}}
function wireSupportRequest(){const email=$("#supportEmail"),password=$("#supportPassword"),ack=$("#supportAcknowledge"),start=$("#startSupportRequest"),status=$("#supportStatus");let acknowledged=false;const update=()=>{const ready=email.validity.valid&&password.value.length>0&&acknowledged;start.disabled=!ready;ack.classList.toggle("acknowledged",acknowledged);ack.setAttribute("aria-pressed",acknowledged);ack.textContent=tr(acknowledged?"Acknowledged":"Acknowledge")};email.addEventListener("input",update);password.addEventListener("input",update);ack.onclick=()=>{acknowledged=!acknowledged;update()};start.onclick=()=>{if(start.disabled)return;password.value="";acknowledged=false;update();status.textContent=tr("Support request prepared. Your password was not included or stored.")}}
const tooltip=document.createElement("div");tooltip.className="hci-tooltip";tooltip.hidden=true;document.body.append(tooltip);
const navHelp={Overview:"Business overview",Orders:"Review and fulfill orders",Products:"Manage your product catalog",Inventory:"Track stock and restocking",Marketplace:"Find SMB suppliers and partners",Logistics:"Manage shipments and couriers",Accounting:"Review income, expenses, and tax",Reports:"Open business reports"};
Object.entries(navHelp).forEach(([view,help])=>$$('[data-view="'+view+'"]').forEach(el=>{el.dataset.tooltip=help;el.title=help}));
function wireTooltips(){$$("[data-tooltip]").forEach(el=>{if(el.dataset.tooltipReady)return;el.dataset.tooltipReady="true";const show=()=>{tooltip.textContent=el.dataset.tooltip;tooltip.hidden=false;const r=el.getBoundingClientRect(),w=tooltip.offsetWidth;tooltip.style.left=Math.max(8,Math.min(innerWidth-w-8,r.left+r.width/2-w/2))+"px";tooltip.style.top=Math.min(innerHeight-tooltip.offsetHeight-8,r.bottom+8)+"px"};const hide=()=>tooltip.hidden=true;el.addEventListener("mouseenter",show);el.addEventListener("mouseleave",hide);el.addEventListener("focus",show);el.addEventListener("blur",hide)})}
const openModal=()=>{modal.hidden=false;document.body.classList.add('locked');$("#formBody").hidden=false;$("#success").hidden=true};const closeModal=()=>{modal.hidden=true;document.body.classList.remove('locked')};$$('[data-add]').forEach(b=>b.onclick=openModal);$$('[data-cancel]').forEach(b=>b.onclick=closeModal);
upload.onclick=()=>photo.click();photo.onchange=()=>{const file=photo.files[0];if(file){upload.style.backgroundImage=`url(${URL.createObjectURL(file)})`;upload.classList.add('has-photo')}};
$("#minus").onclick=()=>stock.value=Math.max(0,Number(stock.value)-1);$("#plus").onclick=()=>stock.value=Number(stock.value)+1;
taxToggle.onclick=()=>{const on=taxToggle.classList.toggle('on');taxToggle.setAttribute('aria-checked',on);taxValue.disabled=!on};
form.onsubmit=e=>{e.preventDefault();$("#formBody").hidden=true;$("#success").hidden=false};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeMenu()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$("#search").focus()}});
let activeTheme=localStorage.getItem("marxia-theme")||(window.matchMedia?.("(prefers-color-scheme: dark)").matches?"dark":"light");
const applyTheme=()=>{localize(document);document.documentElement.dataset.theme=activeTheme;const dark=activeTheme==="dark";$("#themeLabel").textContent=activeLanguage==="es"?(dark?"Oscuro":"Claro"):(dark?"Dark":"Light");$("#themeToggle span").textContent=dark?"☾":"☀";$("#themeToggle").setAttribute("aria-pressed",dark)};
$("#themeToggle").onclick=()=>{activeTheme=activeTheme==="dark"?"light":"dark";localStorage.setItem("marxia-theme",activeTheme);applyTheme()};
const setText=(selector,text)=>{const el=$(selector);if(el)el.textContent=text};
const applyLanguage=()=>{document.documentElement.lang=activeLanguage;const spanish=activeLanguage==="es";$("#languageLabel").textContent=spanish?"ES":"EN";$("#languageToggle span").textContent=spanish?"EN":"ES";$("#languageToggle").setAttribute("aria-pressed",spanish);$("#search").placeholder=spanish?"Buscar pedidos, productos, clientes…":"Search orders, products, customers…";setText('.account-actions [data-view="Profile"] span',tr("Profile"));setText('.account-actions [data-view="Settings"] span',tr("Settings"));setText(".support-button span",tr("Tech Support"));setText("header [data-add] span",tr("Add product"));setText(".welcome h1",tr("Good morning, Gabriel"));setText("#mobileSectionsToggle b",spanish?"Secciones del panel":"Dashboard sections");setText("#mobileSectionsToggle small",spanish?"Menú":"Menu");setText(".welcome>div:first-child>span",tr("Here’s what’s happening across your business."));const mode=$$(".mode button");if(mode[0])mode[0].textContent="⌂ "+tr("Sell");if(mode[1])mode[1].textContent="▣ "+tr("Buy for my business");$$(".quick-nav [data-view]").forEach(button=>{const label=button.dataset.view,span=$("span",button);if(span)span.textContent=tr(label)});setText(".notice strong",tr("3 items need your attention"));setText(".notice small",tr("Two products are running low and one order is waiting to be dispatched."));setText(".notice>button",tr("Review now"));setText(".section-title h2",tr("Business pulse"));setText(".section-title small",tr("Performance at a glance"));const options=$$("#period option");["Last 7 days","Last 30 days","This year"].forEach((label,i)=>{if(options[i])options[i].textContent=tr(label)});applyTheme()};
$("#languageToggle").onclick=()=>{activeLanguage=activeLanguage==="en"?"es":"en";localStorage.setItem("marxia-language",activeLanguage);applyLanguage();if(businessViews.has(activeView))renderDashboardView(activeView)};
applyBrand();applyLanguage();wireTooltips();
clearDashboardView();



